#!/bin/sh

. /usr/share/debconf/confmodule

chown -R dialtime:dialtime /var/cache/dialtime /var/lib/dialtime /var/log/dialtime
chmod -R 2770 /var/cache/dialtime /var/lib/dialtime /var/log/dialtime
service cron restart
